django/crud_review/crud_review/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('students/', include('students.urls')),
    path('admin/', admin.site.urls),
]

django/crud_review/students/urls.py
from django.urls import path
from . import views

app_name = 'students'

urlpatterns = [
    path('', views.index, name= 'index'),                      # GET /students/
    path('<int:pk>/', views.detail, name= 'detail'),           # GET /students/1/
    path('new/', views.new, name= 'new'),                      # GET,POST /students/new/
    # path('create/', views.create, name= 'create'),           # GET,POST /students/create/ (x)
    path('<int:pk>/edit/', views.edit, name= 'edit'),          # GET,POST /students/1/edit/
    # path('<int:pk>/update/', views.update, name= 'update'),    # POST /students/1/update/ (x) 
    path('<int:pk>/delete/', views.delete, name= 'delete'),    # POST /students/1/delete/ 
]


#  URL Name
# path('주소'/, views.함수, name='이름)
# {% url '이름' %} => 주소
# 
# -장점
# 1. 주소의 변경이 필요할 때, urls.py
# 2. 마지막 '/'를 빼먹는 실수를 차단할 수 있다.

# App Name - 특정 app의 urls.py 자체
# {% url 'app_name:path_name' %} => 주소


# RESTful
# 1. 자원(Resource) - URI
# 2. 행위(Verb) - HTTP Method (GET, POST, ..)
# 3. 표현(Representations) - 자원 + 행위

# Django는  PUT/PATCH/DELETE 불가능. 따라서..
# GET   /students/2/edit/ => 수정 페이지 부여줌
# POST  /students/2/edit/ => 수정 작업 수행

# ex)
# GET     /users/1 => user 1번 가져옴
# PUT     /users/1 => user 1번 가져옴
# GET     /users/1 => user 1번 가져옴
# 
# 

django/crud_review/students/models.py
from django.db import models

# Create your models here.
class Students(models.Model):
    #id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=10)
    age = models.IntegerField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now= True)

    

    # 1. python manage.py makemigrations

    # 2. python manage.py migrate 실행

# Student : Comment = 1: N


class Comment(models.Model):
    content = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now= True)
    student = models.ForeignKey(Students, on_delete = models.CASCADE)
    # CASCADE- 1:N에서 1이 삭제되면 N도 삭제
    # PROTECT- 1을 삭제하려 할 때, N이 있으면 삭제 불가능
    # SET_NULL - 1이 삭제가 되면, N의 컬럼에 NULL로 설정
    # DO_NOTHING - 아무것도 하지 않음


    #  1. 1번 학생(1) 가져오기
    #  student = Students.objects.get(pk=1)
    #  
    #  2. 댓글(N) 생성
    #  comment = Comment()
    #  comment.content = 'First Comment'
    #  comment.student = student        =     commnet.student_id = student.pk
    #  comment.save()


    #  3. 댓글(N)로 부터 학생(1) 불러오기
    #  comment.student #=> student 인스턴스 자체
    #  comment.student.name => 학생 이름
    #  comment.student.age => 학생 나이

    #  4. 학생(1)으로부터 댓글(N) 불러오기
    #  student.comment_set.all() => comment QuerySet

django/crud_review/students/views.py
from django.shortcuts import render, redirect
from .models import Students

# Create your views here.
def index(request):
    students = Students.objects.all().order_by('-id')
    context ={
        'students': students,
    }
    return render(request, 'students/index.html', context)

def detail(request, pk):
    students = Students.objects.get(pk=pk)

    context = {
        'students':students,
    }
    return render(request, 'students/detail.html', context)

def delete(request,pk):

    if request.method == 'POST':
        student = Students.objects.get(pk=pk)
        student.delete()
    
        return redirect('students:index')

def new(request):
    if request.method == 'POST':
        # students를 생성함.
        name = request.POST.get('name')
        age = request.POST.get('age')

        students = Students.objects.create(name= name , age = age)
        students.save()

        return redirect('/students/')

    else:        
        # new page를 보여주면 됨.
        return render(request, 'students/new.html')

    

# def create(request):
#     name = request.POST.get('name')
#     age = request.POST.get('age')

#     students = Students.objects.create(name= name , age = age)
#     students.save()

#     return redirect('/students/')

def edit(request, pk):
    students = Students.objects.get(pk=pk)
    
    if request.method == 'POST':
        # update (def update)
        name = request.POST.get('name')
        age = request.POST.get('age')
        
    
        students.name = name
        students.age = age
        students.save()

        return redirect('/students/')

    else:
        # 수정하는 페이지 보여줌 
        context ={
            'students':students,
        }
        return render(request, 'students/edit.html', context)




    

# def update(request,pk):

#     name = request.POST.get('name')
#     age = request.POST.get('age')
#     students = Students.objects.get(pk=pk)
    
#     students.name = name
#     students.age = age
#     students.save()

#     return redirect('/students/')

django/crud_review/students/templates/students/detail.html
{% extends 'base.html' %}

{% block body %}

<h1>학생 상세 정보</h1>

<h3> {{students.id}}번 학생의 이름은 : {{students.name}}</h3>
<h3> {{students.id}}번 학생의 나이는 : {{students.age}}</h3>
<h3> 생성 시간 : {{students.created_at}}</h3>
<h3> 수정 시간 : {{students.updated_at}}</h3>

<a href="/students/"><h1>홈</h1></a>
<a href="/students/{{students.pk}}/edit/"><h1>수정하기</h1></a>

<!-- a  tag는 POST 요청 보낼 수 없습니다. 그렇다면 form tag! -->
<!-- <a href="{% url 'delete' students.pk %}"> 삭제</a> -->

<form action="{% url 'students:delete' student.pk %}" method="POST">
    {% csrf_token %}
    <input type="submit" value = "delete">
</form>


{% endblock %}

django/crud_review/students/templates/students/edit.html
{% extends 'base.html' %}

{% block body %}

<form action="" method="POST">
    {% csrf_token %}
    <label for="">이름 : </label>
    <input type="text" name="name" value="{{students.name}}">
    <label for="">나이 :</label>
    <input type="int" name="age" value="{{students.age}}">
    <input type="submit">
</form>

<a href="/students/">취소하기</a>

{% endblock %}

django/crud_review/students/templates/students/index.html
{% extends 'base.html' %}

{% block body%}

<h1>학생들</h1>

{% for student in students %}
<li><a href="/students/{{student.id}}/"><h3>{{student.id}}번 학생</h3></a>
     <p>{{student.name}}는 {{student.age}}세</p>
</li>

{% endfor %}

<a href="/students/new">학생 추가하기</a>

{% endblock %}

django/crud_review/students/templates/students/new.html
{% extends 'base.html' %}

{% block body %}

<h1>Create Student</h1>
<!-- {% url 'students:create' %} -->
<!-- 액션의 값이 없으면, 자기 자신의 주소로 요청을 보냄 -->
<form action="" method="POST">
    {% csrf_token %}
    <label for="">이름 : </label>
    <input type="text" name="name">
    <label for="">나이 :</label>
    <input type="number" name="age">
    <input type="submit">
</form>

<a href="/students/"><h1>홈</h1></a>

{% endblock %}